// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvgMHWeO_HNmFmeodXdLOT1wTfvguQcSI',
    appId: '1:146182530351:web:a0d6bfa841649721cbadda',
    messagingSenderId: '146182530351',
    projectId: 'flutter-test-6bbbf',
    authDomain: 'flutter-test-6bbbf.firebaseapp.com',
    storageBucket: 'flutter-test-6bbbf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB66t6qiooRR3nV6sa_xM7brd4QfOJk1lY',
    appId: '1:146182530351:android:7a545637dbe51d06cbadda',
    messagingSenderId: '146182530351',
    projectId: 'flutter-test-6bbbf',
    storageBucket: 'flutter-test-6bbbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxxj0EhhcaepGiVfTd_bwUx3iHjfdcTGM',
    appId: '1:146182530351:ios:7ead405ed07c6427cbadda',
    messagingSenderId: '146182530351',
    projectId: 'flutter-test-6bbbf',
    storageBucket: 'flutter-test-6bbbf.firebasestorage.app',
    iosBundleId: 'com.luevano.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxxj0EhhcaepGiVfTd_bwUx3iHjfdcTGM',
    appId: '1:146182530351:ios:7ead405ed07c6427cbadda',
    messagingSenderId: '146182530351',
    projectId: 'flutter-test-6bbbf',
    storageBucket: 'flutter-test-6bbbf.firebasestorage.app',
    iosBundleId: 'com.luevano.app',
  );
}
